"""add_uniq_constraint

Revision ID: 70fcd6310575
Revises: be0e1698c4e2
Create Date: 2023-08-23 13:50:31.399376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fcd6310575'
down_revision = 'be0e1698c4e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_friend', 'friends', ['user_id', 'friend_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_friend', 'friends', type_='unique')
    # ### end Alembic commands ###
